parameters:
  logging_level: !php/const Monolog\Logger::INFO

services:
  logger:
    public: true
    class: Monolog\Logger
    arguments:
      - 'handler'
    calls:
      - [pushHandler, ['@logging.handler']]

  logging.formatter:
    class: Monolog\Formatter\LineFormatter
    public: false
    arguments:
      - '%%message%% %%context%% %%extra%%'

  logging.handler:
    class: Monolog\Handler\StreamHandler
    public: false
    arguments:
      - 'php://stderr'
      - '%logging_level%'
    calls:
      - [setFormatter, ['@logging.formatter']]

  handler.phpinfo:
    public: true
    class: CrazyLister\Serverless\PHPInfo

  handler.printHelloWorld:
    public: true
    class: CrazyLister\Serverless\PrintHelloWorld

