service: php-lambda

provider:
  name: aws
  runtime: nodejs6.10

package:
  exclude:
    - '*'
    - '**'
  include:
    - services.yml
    - handler.js
    - handler.php
    - bash
    - php
    - phplibs/**
    - phpini/**
    - src/**
    - vendor/**

functions:
  phpinfo:
    handler: handler.handle
    environment:
      HANDLER: handler.phpinfo
    events:
      - http:
          path: phpinfo
          method: get

  printHelloWorld:
    handler: handler.handle
    environment:
      HANDLER: handler.printHelloWorld
    events:
      - http:
          path: printHelloWorld
          method: get


